// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBZtfWKzysE66EzE78uyOg2r6TsBzQT08',
    appId: '1:883652005967:web:5082cd3ed829d9274b1a3a',
    messagingSenderId: '883652005967',
    projectId: 'partylander',
    authDomain: 'partylander.firebaseapp.com',
    databaseURL: 'https://partylander-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'partylander.appspot.com',
    measurementId: 'G-5XJYXPFQ2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ_Uk7NbTHzPw_UqraKLPfPc97dbeujLo',
    appId: '1:883652005967:android:5f02c888810fb23e4b1a3a',
    messagingSenderId: '883652005967',
    projectId: 'partylander',
    databaseURL: 'https://partylander-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'partylander.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJlz4KC9Clc06_UajzkIsZPjxSfNfytoA',
    appId: '1:883652005967:ios:cce2cf32f5dc20ac4b1a3a',
    messagingSenderId: '883652005967',
    projectId: 'partylander',
    databaseURL: 'https://partylander-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'partylander.appspot.com',
    iosClientId: '883652005967-utd21nnutnnld6ubgqbukfv0ch3992e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.partylander',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJlz4KC9Clc06_UajzkIsZPjxSfNfytoA',
    appId: '1:883652005967:ios:cce2cf32f5dc20ac4b1a3a',
    messagingSenderId: '883652005967',
    projectId: 'partylander',
    databaseURL: 'https://partylander-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'partylander.appspot.com',
    iosClientId: '883652005967-utd21nnutnnld6ubgqbukfv0ch3992e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.partylander',
  );
}
